### PR TITLE
Adding AWS Athena as data source

### PR DESCRIPTION
**Pull request by bhavintandel**
Added the snippet to read data from AWS Athena using PyAthena in reference to the [issue](https://github.com/mindsdb/mindsdb/issues/874)

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/> 
   - - -
   ***I have read the CLA Document and I hereby sign the CLA***
   - - - 
   <sub>You can retrigger this bot by commenting **recheckcla** in this Pull Request</sub>

**Comment by bhavintandel** [comment]
**_I have read the CLA Document and I hereby sign the CLA_**

**Comment by bhavintandel** [comment]
recheckcla

**Comment by bhavintandel** [comment]
**recheckcla**

**Review by ZoranPandovski — APPROVED** [review]

**Comment by George3d6** [comment]
Not sure why this was left unmerged for so long, seems perfect, thanks a lot @bhavintandel

**Pull request merged**
