### PR TITLE
stats for tags

### PR DESCRIPTION
**Pull request by maximlopin**
- add support for `tags_delimiter` advanced arg (`','` by default)
- add `'tag_set'` to `stats_v2` which is the set of all tags
- add `'guess_probability'` to `stats_v2` for tags

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
**CLA Assistant Lite** All Contributors have signed the CLA.

**Comment by ZoranPandovski** [comment]
**CLA Assistant Lite** All Contributors have signed the CLA.

**Comment by ZoranPandovski** [comment]
**CLA Assistant Lite** All Contributors have signed the CLA.

**Comment by ZoranPandovski** [comment]
**CLA Assistant Lite** All Contributors have signed the CLA.

**Review by George3d6 — APPROVED** [review]

**Pull request merged**
