### PR TITLE
Added Redshift Datasource

### PR DESCRIPTION
**Pull request by purvimisal**
Added Redshift Datasource as a fix for mindsdb issue [#758 ](https://github.com/mindsdb/mindsdb/issues/758)

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
****CLA Assistant Lite bot**** All contributors have signed the CLA  ✍️

**Review by ZoranPandovski — APPROVED** [review]
Looks great, thanks @purvimisal . Can you please just sign the CLA, by adding the comment?

**Comment by George3d6** [comment]
Is `postgres` the default redshift user ?

Also, can you please add the export logic for this datasource, similar to what we do for postgres here: https://github.com/mindsdb/mindsdb_native/blob/stable/mindsdb_native/__init__.py#L32

**Comment by purvimisal** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by purvimisal** [comment]
@George3d6  Default user for redshift is actually 'awsuser' and default database is 'dev' . 
I will go ahead and change it and also add the export logic for this datasource.

**Pull request merged**
