### PR TITLE
Release

### PR DESCRIPTION
**Pull request by maximlopin**
- Training a predictor now can fail if accuracy is worse than random (only for output types: categorical, numerical)
- Add some stats for `TAGS` data type
- `'guess_accuracy'` key in stats_v2 for categorical columns

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
**CLA Assistant Lite** All Contributors have signed the CLA.

**Comment by ZoranPandovski** [comment]
**CLA Assistant Lite** All Contributors have signed the CLA.

**Comment by ZoranPandovski** [comment]
**CLA Assistant Lite** All Contributors have signed the CLA.

**Comment by ZoranPandovski** [comment]
**CLA Assistant Lite** All Contributors have signed the CLA.

**Comment by ZoranPandovski** [comment]
**CLA Assistant Lite** All Contributors have signed the CLA.

**Comment by ZoranPandovski** [comment]
**CLA Assistant Lite** All Contributors have signed the CLA.

**Comment by ZoranPandovski** [comment]
**CLA Assistant Lite** All Contributors have signed the CLA.

**Review by George3d6 — APPROVED** [review]

**Pull request merged**
