### PR TITLE
Fix pyathena dependency

### PR DESCRIPTION
**Pull request by wwaitann**
## Why
-  PyAthena 2.0.0 contains breaking change, so mindsdb_native cannot load athena_ds .
    - Error message: `Athena Datasource is not available by default. If you wish to use it, please install mindsdb_native[extra_data_sources]` 
    - [PyAthena difference](https://github.com/laughingman7743/PyAthena/compare/v1.11.2...v2.0.0#diff-ab524ae115319db0115b030d3d4aa3f01494d9ce1843ff84d6c6186495313eacL62)

## How
- Update pyathena minimum version to 2.0.0
- Update as_pandas import path

### CODE REVIEW

**Comment by wwaitann** [comment]
CI fails by lack of ‘DATABASE_CREDENTIALS' environment variable.
How can I  fix it?

**Comment by ZoranPandovski** [comment]
Hi @ytannai. You are getting that warning because Pyathena must be installed from the optional_requirements_extra_data_sources requirements file

**Comment by wwaitann** [comment]
@ZoranPandovski Thanks for your reply.

As you mentioned, we get warning when extra data sources not installed.
And we get warning message too when install `PyAthena >= 1.11.2`. `PyAthena >= 1.11.2` means `PyAthena == 2.0.0` today.

Because there are incompatible directory structure, AthenaDS is unavailable with extra data sources installation or not.
To fix this, I updated PyAthena minimum version and fixed import path.

In addition, I fixed constructor problem.

**Comment by George3d6** [comment]
Not sure why tests are failing.

**Comment by George3d6** [comment]
changed base to staging and re-running tests

**Comment by George3d6** [comment]
Ah, ****, failing because now that we use the credentials as part of the tests, we can't PR stuff directly into staging from 3rd party branches -_-, this might prove to be a fairly annoying issues. This looks fine, so merging now.

**Pull request merged**
