### PR TITLE
Fix PyPI badge to point to mindsdb_native

### PR DESCRIPTION
**Pull request by abitrolly**

### CODE REVIEW

**Review by ZoranPandovski — APPROVED** [review]
Thanks

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
****CLA Assistant Lite bot**** All contributors have signed the CLA  ✍️

**Comment by abitrolly** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
